System:
  pointCloudTopic: "velodyne_points" 
  imuTopic: "handsfree/imu"
  odomTopic: "odometry/imu"

  numberOfCores: 8

  mode: "lio"                                  # "lio" or "relo"

  lidarFrame: "base_link"
  baselinkFrame: "base_link"
  odometryFrame: "odom"
  mapFrame: "map"

  savePCDDirectory: "/home/yixin/lio-sam/src/data"
  saveSessionDirectory: "/home/yixin/lio-sam/src/session"

Sensors:
  sensor: velodyne                              # lidar sensor type, 'velodyne' or 'ouster' or 'livox' or 'robosense'
  N_SCAN: 16                                    # number of lidar channel (i.e., Velodyne/Ouster: 16, 32, 64, 128, Horizon: 6, mid40: 1, mid360: 4, avia: 8)
  Horizon_SCAN: 1800                            # lidar horizontal resolution (Velodyne: 1800, Ouster: 512, 1024, 2048)

  have_ring_time_channel: true                  # some datasets, such as nclt and m2dgr has no ring or time channel

  downsampleRate: 1                             # line - default: 1. e.g., 16 = 64 / 4, 16 = 16 / 1
  point_filter_num: 1                           # point - default: 3. e.g., 16: 1, 32: 5, 64: 8

  lidarMinRange: 2.0                            # default: 1.0
  lidarMaxRange: 100.0                          # default: 100.0

  imuType: 0                                    # 0: 6-axis (default)  1: 9-axis
  imuRate: 500.0
  imuAccNoise: 3.9939570888238808e-03
  imuGyrNoise: 1.5636343949698187e-03
  imuAccBiasN: 6.4356659353532566e-05
  imuGyrBiasN: 3.5640318696367613e-05
  imuGravity: 9.80511
  imuRPYWeight: 0.01

  correct: false

  # Extrinsics: (lidar -> imu)
  # extrinsicTrans: [ 0.071, -0.053, 0.097 ]
  # extrinsicRot: [ 0.9935, -0.0140, -0.1128,
  #                 0.0137,  0.9999, -0.0040,
  #                 0.1128,  0.0024,  0.9936 ]

  extrinsicTrans: [ 0.031, -0.10, 0.11]
  extrinsicRot: [ 0.9994142, 0.03275957, 0.00990251,
                  -0.03266505,  0.99942062, -0.00956125,
                  -0.01021,  0.00923218,  0.99990526]
  
  # Extrinsics: 9-axis
  extrinsicRPY: [ 0, -1,  0,
                  1,  0,  0,
                  0,  0,  1 ]
  
Mapping:
  z_tollerance: 1000                            # meters
  rotation_tollerance: 1000                     # radians

  regMethod: "DIRECT1"                          # "DIRECT1", "DIRECT7", "GICP_OMP", "KDTREE"
  ndtResolution: 1.0                            # meters
  ndtEpsilon: 0.01

  timeInterval: 0.2                             # seconds, relo interval

  mappingProcessInterval: 0.0                   # seconds, mapping interval

  mappingSurfLeafSize: 0.2                      # default: 0.4 - outdoor, 0.2 - indoor

  surroundingkeyframeAddingDistThreshold: 0.8   # meters, regulate keyframe adding threshold
  surroundingkeyframeAddingAngleThreshold: 0.2  # radians, regulate keyframe adding threshold
  surroundingKeyframeDensity: 2.0               # meters, downsample surrounding keyframe poses   
  surroundingKeyframeSearchRadius: 20.0         # meters, within n meters scan-to-map optimization (when loop closure disabled)
  surroundingKeyframeMapLeafSize: 0.5           # downsample local map point cloud

  globalMapVisualizationSearchRadius: 1000.0    # meters, global map visualization radius
  globalMapVisualizationPoseDensity: 10.0       # meters, global map visualization keyframe density
  globalMapVisualizationLeafSize: 1.0           # meters, global map visualization cloud density